name: metric
channels:
  - conda-forge
  - defaults
dependencies:
  # install pyTESB and pyProSail from github and pyMETRIC locally with flit after setting up this env
  - rasterio
  - xarray
  - pyproj
  - pandas
  - numpy
  - scipy
  - pip:
    - ipykernel
    - rioxarray
    - daymetpy
    - git+https://github.com/hectornieto/pyPro4Sail@master
    - git+https://github.com/hectornieto/pyTSEB@master
    - flit
    - geopandas
    - pvlib
    - timezonefinder
