[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "pyMETRIC"
author = "Ryan Avery"
author-email = "ravey@ucsb.edu"
classifiers = ["License :: OSI Approved :: MIT License"]

